// Generated by gencpp from file book_grab/hh_eyeResponse.msg
// DO NOT EDIT!


#ifndef BOOK_GRAB_MESSAGE_HH_EYERESPONSE_H
#define BOOK_GRAB_MESSAGE_HH_EYERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace book_grab
{
template <class ContainerAllocator>
struct hh_eyeResponse_
{
  typedef hh_eyeResponse_<ContainerAllocator> Type;

  hh_eyeResponse_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , a(0.0)  {
    }
  hh_eyeResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , a(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::book_grab::hh_eyeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::book_grab::hh_eyeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct hh_eyeResponse_

typedef ::book_grab::hh_eyeResponse_<std::allocator<void> > hh_eyeResponse;

typedef boost::shared_ptr< ::book_grab::hh_eyeResponse > hh_eyeResponsePtr;
typedef boost::shared_ptr< ::book_grab::hh_eyeResponse const> hh_eyeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::book_grab::hh_eyeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::book_grab::hh_eyeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::book_grab::hh_eyeResponse_<ContainerAllocator1> & lhs, const ::book_grab::hh_eyeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::book_grab::hh_eyeResponse_<ContainerAllocator1> & lhs, const ::book_grab::hh_eyeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace book_grab

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::book_grab::hh_eyeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::book_grab::hh_eyeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::book_grab::hh_eyeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::book_grab::hh_eyeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::book_grab::hh_eyeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::book_grab::hh_eyeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::book_grab::hh_eyeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "048816fafbfc26a9b1dace8fa24075f0";
  }

  static const char* value(const ::book_grab::hh_eyeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x048816fafbfc26a9ULL;
  static const uint64_t static_value2 = 0xb1dace8fa24075f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::book_grab::hh_eyeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "book_grab/hh_eyeResponse";
  }

  static const char* value(const ::book_grab::hh_eyeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::book_grab::hh_eyeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 a\n"
"\n"
;
  }

  static const char* value(const ::book_grab::hh_eyeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::book_grab::hh_eyeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hh_eyeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::book_grab::hh_eyeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::book_grab::hh_eyeResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOOK_GRAB_MESSAGE_HH_EYERESPONSE_H
