// Generated by gencpp from file book_grab/hh_eye.msg
// DO NOT EDIT!


#ifndef BOOK_GRAB_MESSAGE_HH_EYE_H
#define BOOK_GRAB_MESSAGE_HH_EYE_H

#include <ros/service_traits.h>


#include <book_grab/hh_eyeRequest.h>
#include <book_grab/hh_eyeResponse.h>


namespace book_grab
{

struct hh_eye
{

typedef hh_eyeRequest Request;
typedef hh_eyeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct hh_eye
} // namespace book_grab


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::book_grab::hh_eye > {
  static const char* value()
  {
    return "0b2f3d88a0bcfdb07982649c860629f6";
  }

  static const char* value(const ::book_grab::hh_eye&) { return value(); }
};

template<>
struct DataType< ::book_grab::hh_eye > {
  static const char* value()
  {
    return "book_grab/hh_eye";
  }

  static const char* value(const ::book_grab::hh_eye&) { return value(); }
};


// service_traits::MD5Sum< ::book_grab::hh_eyeRequest> should match
// service_traits::MD5Sum< ::book_grab::hh_eye >
template<>
struct MD5Sum< ::book_grab::hh_eyeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::book_grab::hh_eye >::value();
  }
  static const char* value(const ::book_grab::hh_eyeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::book_grab::hh_eyeRequest> should match
// service_traits::DataType< ::book_grab::hh_eye >
template<>
struct DataType< ::book_grab::hh_eyeRequest>
{
  static const char* value()
  {
    return DataType< ::book_grab::hh_eye >::value();
  }
  static const char* value(const ::book_grab::hh_eyeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::book_grab::hh_eyeResponse> should match
// service_traits::MD5Sum< ::book_grab::hh_eye >
template<>
struct MD5Sum< ::book_grab::hh_eyeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::book_grab::hh_eye >::value();
  }
  static const char* value(const ::book_grab::hh_eyeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::book_grab::hh_eyeResponse> should match
// service_traits::DataType< ::book_grab::hh_eye >
template<>
struct DataType< ::book_grab::hh_eyeResponse>
{
  static const char* value()
  {
    return DataType< ::book_grab::hh_eye >::value();
  }
  static const char* value(const ::book_grab::hh_eyeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BOOK_GRAB_MESSAGE_HH_EYE_H
