// Generated by gencpp from file book_grab/try_getin.msg
// DO NOT EDIT!


#ifndef BOOK_GRAB_MESSAGE_TRY_GETIN_H
#define BOOK_GRAB_MESSAGE_TRY_GETIN_H

#include <ros/service_traits.h>


#include <book_grab/try_getinRequest.h>
#include <book_grab/try_getinResponse.h>


namespace book_grab
{

struct try_getin
{

typedef try_getinRequest Request;
typedef try_getinResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct try_getin
} // namespace book_grab


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::book_grab::try_getin > {
  static const char* value()
  {
    return "387888aa2537f7f5ee4e59936afe4d79";
  }

  static const char* value(const ::book_grab::try_getin&) { return value(); }
};

template<>
struct DataType< ::book_grab::try_getin > {
  static const char* value()
  {
    return "book_grab/try_getin";
  }

  static const char* value(const ::book_grab::try_getin&) { return value(); }
};


// service_traits::MD5Sum< ::book_grab::try_getinRequest> should match
// service_traits::MD5Sum< ::book_grab::try_getin >
template<>
struct MD5Sum< ::book_grab::try_getinRequest>
{
  static const char* value()
  {
    return MD5Sum< ::book_grab::try_getin >::value();
  }
  static const char* value(const ::book_grab::try_getinRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::book_grab::try_getinRequest> should match
// service_traits::DataType< ::book_grab::try_getin >
template<>
struct DataType< ::book_grab::try_getinRequest>
{
  static const char* value()
  {
    return DataType< ::book_grab::try_getin >::value();
  }
  static const char* value(const ::book_grab::try_getinRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::book_grab::try_getinResponse> should match
// service_traits::MD5Sum< ::book_grab::try_getin >
template<>
struct MD5Sum< ::book_grab::try_getinResponse>
{
  static const char* value()
  {
    return MD5Sum< ::book_grab::try_getin >::value();
  }
  static const char* value(const ::book_grab::try_getinResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::book_grab::try_getinResponse> should match
// service_traits::DataType< ::book_grab::try_getin >
template<>
struct DataType< ::book_grab::try_getinResponse>
{
  static const char* value()
  {
    return DataType< ::book_grab::try_getin >::value();
  }
  static const char* value(const ::book_grab::try_getinResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BOOK_GRAB_MESSAGE_TRY_GETIN_H
