// Generated by gencpp from file book_grab/try_getinResponse.msg
// DO NOT EDIT!


#ifndef BOOK_GRAB_MESSAGE_TRY_GETINRESPONSE_H
#define BOOK_GRAB_MESSAGE_TRY_GETINRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace book_grab
{
template <class ContainerAllocator>
struct try_getinResponse_
{
  typedef try_getinResponse_<ContainerAllocator> Type;

  try_getinResponse_()
    : result(0)  {
    }
  try_getinResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::book_grab::try_getinResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::book_grab::try_getinResponse_<ContainerAllocator> const> ConstPtr;

}; // struct try_getinResponse_

typedef ::book_grab::try_getinResponse_<std::allocator<void> > try_getinResponse;

typedef boost::shared_ptr< ::book_grab::try_getinResponse > try_getinResponsePtr;
typedef boost::shared_ptr< ::book_grab::try_getinResponse const> try_getinResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::book_grab::try_getinResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::book_grab::try_getinResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::book_grab::try_getinResponse_<ContainerAllocator1> & lhs, const ::book_grab::try_getinResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::book_grab::try_getinResponse_<ContainerAllocator1> & lhs, const ::book_grab::try_getinResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace book_grab

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::book_grab::try_getinResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::book_grab::try_getinResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::book_grab::try_getinResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::book_grab::try_getinResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::book_grab::try_getinResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::book_grab::try_getinResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::book_grab::try_getinResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::book_grab::try_getinResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::book_grab::try_getinResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "book_grab/try_getinResponse";
  }

  static const char* value(const ::book_grab::try_getinResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::book_grab::try_getinResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"\n"
;
  }

  static const char* value(const ::book_grab::try_getinResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::book_grab::try_getinResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct try_getinResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::book_grab::try_getinResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::book_grab::try_getinResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOOK_GRAB_MESSAGE_TRY_GETINRESPONSE_H
